name: Compile and Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ask-cli-artifact
          path: target/${{ matrix.target }}/release/ask-cli

      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/${{ matrix.target }}/release/ask/cli